Hotfix branch creator fixes

diff --git a/.github/workflows/create-hotfix-branch.yaml b/.github/workflows/create-hotfix-branch.yaml
--- a/.github/workflows/create-hotfix-branch.yaml
+++ b/.github/workflows/create-hotfix-branch.yaml
@@ -4,6 +4,7 @@
 
 name: Create hotfix branch
 
+#Trigger the workflow manually.
 on:
   workflow_dispatch:
     inputs:
@@ -12,7 +13,6 @@ on:
         description: 'Select action'
         required: true
         default: build-and-deploy
-        # GitHub doesn't have native radio buttons; use allowed values
         type: choice
         options:
           - build
@@ -42,7 +42,6 @@ env:
 permissions:
   contents: write
 
-#A job has a sequential list of steps. Several jobs can be run in parallel or chained.
 jobs:
   create-hotfix-branch:
 
@@ -51,7 +50,7 @@ jobs:
 
     steps:
         #Checkout the parent branch specifically since we are creating the new one from it.
-      - name: Checkout code
+      - name: Repository checkout
         uses: actions/checkout@v4
         with:
           ref: ${{ env.PARENT_BRANCH }}
@@ -85,26 +84,8 @@ jobs:
             echo "✅ Version number ${VERSION_NUMBER} is consistent with the format"
           fi
 
-        #Read and increment the version number.
-      - name: Increment the version
-        run: |
-          #Read the version number.
-          VERSION_MAJOR=$(echo ${VERSION_NUMBER} | awk -F '.' '{print $1}' | tr -d '\n')
-          VERSION_MINOR=$(echo ${VERSION_NUMBER} | awk -F '.' '{print $2}' | tr -d '\n')
-          VERSION_PATCH=$(echo ${VERSION_NUMBER} | awk -F '.' '{print $3}' | tr -d '\n')
-
-          echo "Version major: $VERSION_MAJOR"
-          echo "Version minor: $VERSION_MINOR"
-          echo "Version patch: $VERSION_PATCH"
-
-          #Increment the patch version.
-          VERSION_NUMBER="$VERSION_MAJOR.$VERSION_MINOR.$((VERSION_PATCH + 1))"
-          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
-          echo "Incremented version number: ${VERSION_NUMBER}"
-
         #Prepare the new branch name with the necessary appends.
-      - name: Prepare release branch name
-        id: meta
+      - name: Prepare hotfix branch name
         run: | 
           #Append the necessary components.
           NEW_BRANCH_NAME="hotfix/${VERSION_NUMBER}"
@@ -126,7 +107,6 @@ jobs:
           #Write the new version to the version file.
           jq ".version = \"${RC_VERSION}\"" ${VERSION_FILE} > temp.json && mv temp.json ${VERSION_FILE}
 
-          #echo "Release candidate version in version file: $(jq -r '.version' ${VERSION_FILE} | tr -d '\n')
           RC_VERSION_READ_BACK=$(jq -r '.version' ${VERSION_FILE} | tr -d '\n')
           echo "Written release candidate version: $RC_VERSION_READ_BACK"
 
@@ -156,8 +136,6 @@ jobs:
 
           #Push the tag.
           git push origin ${RC_VERSION}
-
-      #Build.
 
       #Prepare the image tag with the necessary appends.
       - name: Prepare image tag
@@ -207,8 +185,11 @@ jobs:
         run: |
           docker push ${ECR_REPOSITORY_URL}/${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}
 
-      #Deployment. The .env file must be copied to the deployment repository regardless whether the file is deployed or not. But why though??
-      #It is better not to copy since a change would trigger a deployment even if the image tag is not changed. So, only copy the .env file if the deploy option is selected.
+      ###############################################
+      #Deployment. 
+      ###############################################
+      #It is better not to copy the .env file if the deployment option has not been selected, since a change in the .env would trigger a deployment even 
+      #which would contradict the intention of the user who selected the build option only. Therefore, only copy the .env file if the buil-and-deploy option is selected.
 
       #Checkout the gitops repository.
       - name: Checkout code
@@ -216,14 +197,13 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: ${{ env.DEPLOYMENT_REPOSITORY }}
-          #token: ${{ secrets.DEPLOYMENT_REPOSITORY_TOKEN }}
           ssh-key: ${{ secrets.DEPLOYMENT_REPOSITORY_SSH_PRIVATE_KEY }}
           path: ${{ env.DEPLOYMENT_REPOSITORY_PATH }}
           clean: true      #Cleans the workspace before checking out code.
           fetch-depth: 0   #Required to push back
 
-        #Copy environment variables to the deployment repository.
-      - name: Copy the .env file
+        #Copy the .env file to the deployment repository.
+      - name: Copy the .env file to the deployment repository
         if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
         run: |
           cp ${QA_ENVIRONMENT_SOURCE_FILE} ${DEPLOYMENT_REPOSITORY_PATH}/${QA_ENVIRONMENT_DESTINATION_FILE}
@@ -231,9 +211,9 @@ jobs:
 
           #Verify the change.
           if [[ -f "${QA_ENVIRONMENT_DESTINATION_FILE}" ]]; then
-            echo "✅ .env file exists"
+            echo "✅ .env file exists in the destination"
           else
-            echo "❌ .env file does not exist!"
+            echo "❌ .env file does not exist in the destination!"
             exit 1
           fi
 
@@ -249,6 +229,13 @@ jobs:
             #Verify the change.
             TAG_READ_BACK=$(yq '.containers[] | select(.name == env(DEPLOYMENT_MANIFEST_SERVICE_NAME)) | .tag' "${QA_ENVIRONMENT_VALUES_FILE}")
             echo "Tag read back: $TAG_READ_BACK"
+
+            if [[ "$TAG_READ_BACK" == "${IMAGE_TAG}" ]]; then
+              echo "✅ Image tag updated successfully"
+            else
+              echo "❌ Image tag update failed!"
+              exit 1
+            fi
 
       #Commit and push the change to the deployment repository.
       - name: Commit and push
