Improvements to the pipeline retagging for prod

diff --git a/.github/workflows/tag-for-production.yaml b/.github/workflows/tag-for-production.yaml
--- a/.github/workflows/tag-for-production.yaml
+++ b/.github/workflows/tag-for-production.yaml
@@ -1,6 +1,6 @@
 #Retag an image. Use this to tag an existing image with a new tag. This is useful for promoting an image to production without rebuilding it.
 
-name: List image tags
+name: Tag for production
 
 on:
   workflow_dispatch:
@@ -9,11 +9,10 @@ on:
       INPUT_IMAGE_TAG:
         description: "Source image tag (e.g. 1.0.0-rc.8-RELEASE*)"
         required: true
-        #default: "latest"
 
 #Global environment variables.
 env:
-  INPUT_TAG_TYPE: ${{ github.event.inputs.INPUT_TAG_TYPE }}
+  INPUT_IMAGE_TAG: ${{ github.event.inputs.INPUT_IMAGE_TAG }}
   AWS_REGION: ap-southeast-1
   ECR_REPOSITORY_URL: 104322896078.dkr.ecr.ap-southeast-1.amazonaws.com
   ECR_REPOSITORY_GROUP: s3-app
@@ -28,8 +27,18 @@ jobs:
     #Runner label.
     runs-on: ubuntu-latest
 
+    
     steps:
-      #Log in to the artifact repository.
+        #Validate the input image tag (ex- 1.0.0-rc.8-RELEASE*). Only certain formats are allowed to avoid accidental tagging of wrong images.
+      - name: Validate input image tag
+        run: |
+          #Additional safegaurd to make sure only release branches are built. This is a double check since the version number is already checked to be in the correct format.
+          if [[ "${INPUT_IMAGE_TAG}" != *-rc.*-RELEASE* ]]; then
+          echo "❌ invalid input image tag: ${INPUT_IMAGE_TAG}"
+            exit 1          
+          fi
+
+        #Log in to the artifact repository.
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -37,19 +46,30 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      #Verify that the AWS CLI is configured correctly.
+        #Verify that the AWS CLI is configured correctly.
       - name: Verify AWS CLI
         run: |
           aws --version
           aws sts get-caller-identity
 
-      #Retag an image with the AWS CLI.
-      - name: Retag image
+        #Verify if the input image tag exists in the ECR repository.
+      - name: Verify input image tag
         run: |
           #Get manifest of existing image.
           MANIFEST=$(aws ecr batch-get-image --repository-name ${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME} \
                     --image-ids imageTag=${INPUT_IMAGE_TAG} --query 'images[].imageManifest' --output text)
+          echo "MANIFEST=$MANIFEST" >> $GITHUB_ENV
+          echo "Manifest data: ${MANIFEST}"
 
-          #Create new tag.
+        #Extract the version number from the input image tag to be used as the target image tag.
+      - name: Prepare target image tag
+        run: |          
+          VERSION_NUMBER=$(echo ${INPUT_IMAGE_TAG} | awk -F '-' '{print $1}' | tr -d '\n')
+          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
+          echo "Extracted version number as the target tag: ${VERSION_NUMBER}"
+
+        #Perform the retag.
+      - name: Retag image
+        run: |
           aws ecr put-image --repository-name ${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME} \
-          --image-tag $TARGET_TAG --image-manifest "$MANIFEST"
+          --image-tag ${VERSION_NUMBER} --image-manifest "${MANIFEST}"
